
additional_libs.append('ccdb_sqlite')


# GUI
env.Append(CPPPATH = 'gui/src')
gui_sources = Split("""
	gui/src/gemc_MainGui.cc
	gui/src/detector_editor.cc
	gui/src/runControl/run_control.cc
	gui/src/runControl/primaryTab.cc
	gui/src/runControl/momControls.cc
	gui/src/runControl/vtxControls.cc
	gui/src/camera_control.cc
	gui/src/detector_tree.cc
	gui/src/infos.cc
	gui/src/g4dialog.cc
	gui/src/gsignal.cc
	gui/src/physicsListGui.cc
	gui/src//gtrigger.cc
	utilities/graph.cc""")
env.Library(source = gui_sources, target = "lib/ggui")


# gemc
env.Append(CPPPATH = 'src')
gemc_sources = Split("""
	gemc.cc
	src/dmesg_init.cc
	src/run_conditions.cc
	src/gemc_options.cc
	src/MDetectorConstruction.cc
	src/MEventAction.cc
	src/MPrimaryGeneratorAction.cc
	src/ActionInitialization.cc
	src/MSteppingAction.cc""")

env.Append(LIBPATH = ['lib'])
env.Prepend(LIBS =    'ghitprocess', 'goutput', 'ggui'])
env.Program(source = gemc_sources, target = "gemc")


